name: Build on Push
on: [push]

env:
  REGISTRY: ghcr.io
  DO_PUBLISH: "false"
  publishToNPM: "false"
  SEGMENT_IO_TOKEN: ""
  version: "devel"
  LEEWAY_YARN_MUTEX: "file"
  LEEWAY_WORKSPACE_ROOT: "/github/workspace"
  JAVA_HOME: "/home/gitpod/.sdkman/candidates/java/current"
  # components/dashboard:app need this
  CI: "false"
  BUILD_IMAGE: ghcr.io/zcube/workspace-images/gitpod-dev:arm64
  IMAGE_REPO_BASE: ghcr.io/zcube/gitpod

jobs:
  build-gitpod-amd64:
    runs-on: [self-hosted, linux, x64]
    env:
      GOARCH: amd64
      LEEWAY_REMOTE_CACHE_BUCKET: amd64
      LEEWAY_REMOTE_CACHE_STORAGE: MINIO
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.APP }}
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Filter test job 1
        shell: bash
        run: sed -i 's/[-] test[:]docker/#- test:docker/g' components/BUILD.yaml
      - name: Filter test job 2
        shell: bash
        run: find . | grep BUILD.yaml | xargs -n 1 sed -i 's/[-] [:]dbtest/#- :dbtest/g'
      - name: Change docker tag
        shell: bash
        run: find . | grep BUILD.yaml | xargs -n 1 sed -i 's/commit[-]/commit-${{ env.GOARCH }}-/g'
      - name: Prevent permission error
        shell: bash
        run: sudo chmod 777 /var/run/docker.sock
      - name: build
        uses: docker://ghcr.io/zcube/workspace-images/gitpod-dev:arm64
        with:
          args: |
            /bin/bash -c "sudo chown gitpod:gitpod -R /github/home/ &&
            yarn config set network-timeout 600000 -g &&
            mc config host add minio http://nas.zcube.kr:55090 ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }} &&
            docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} &&
            leeway -DSEGMENT_IO_TOKEN=${{ env.SEGMENT_IO_TOKEN }} -DpublishToNPM=${{ env.publishToNPM }} -DimageRepoBase=${{ env.IMAGE_REPO_BASE }} -Dversion=${{ env.version }}-${{ env.GOARCH }} build components:all-docker --dont-test --dont-retag -j 4"

  build-gitpod-arm64:
    runs-on: [self-hosted, linux, ARM64]
    env:
      GOARCH: arm64
      LEEWAY_REMOTE_CACHE_BUCKET: arm64
      LEEWAY_REMOTE_CACHE_STORAGE: MINIO
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.APP }}
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Filter test job 1
        shell: bash
        run: sed -i 's/[-] test[:]docker/#- test:docker/g' components/BUILD.yaml
      - name: Filter test job 2
        shell: bash
        run: find . | grep BUILD.yaml | xargs -n 1 sed -i 's/[-] [:]dbtest/#- :dbtest/g'
      - name: Change docker tag
        shell: bash
        run: find . | grep BUILD.yaml | xargs -n 1 sed -i 's/commit[-]/commit-${{ env.GOARCH }}-/g'
      - name: Prevent permission error
        shell: bash
        run: sudo chmod 777 /var/run/docker.sock
      - name: build
        uses: docker://ghcr.io/zcube/workspace-images/gitpod-dev:arm64
        with:
          args: |
            /bin/bash -c "sudo chown gitpod:gitpod -R /github/home/ &&
            yarn config set network-timeout 600000 -g &&
            mc config host add minio http://nas.zcube.kr:55090 ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }} &&
            docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} &&
            leeway -DSEGMENT_IO_TOKEN=${{ env.SEGMENT_IO_TOKEN }} -DpublishToNPM=${{ env.publishToNPM }} -DimageRepoBase=${{ env.IMAGE_REPO_BASE }} -Dversion=${{ env.version }}-${{ env.GOARCH }} build components:all-docker --dont-test --dont-retag -j 4"

  merge-gitpod:
    needs: [build-gitpod-arm64, build-gitpod-amd64]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.APP }}
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: build
        shell: bash
        run: |
            /bin/bash -c " \
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/agent-smith:devel                       --amend ${{ env.IMAGE_REPO_BASE }}/agent-smith:devel-arm64                    --amend ${{ env.IMAGE_REPO_BASE }}/agent-smith:devel-amd64                          && docker manifest push ${{ env.IMAGE_REPO_BASE }}/agent-smith:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/blobserve:devel                         --amend ${{ env.IMAGE_REPO_BASE }}/blobserve:devel-arm64                      --amend ${{ env.IMAGE_REPO_BASE }}/blobserve:devel-amd64                            && docker manifest push ${{ env.IMAGE_REPO_BASE }}/blobserve:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ca-updater:devel                        --amend ${{ env.IMAGE_REPO_BASE }}/ca-updater:devel-arm64                     --amend ${{ env.IMAGE_REPO_BASE }}/ca-updater:devel-amd64                           && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ca-updater:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/content-service:devel                   --amend ${{ env.IMAGE_REPO_BASE }}/content-service:devel-arm64                --amend ${{ env.IMAGE_REPO_BASE }}/content-service:devel-amd64                      && docker manifest push ${{ env.IMAGE_REPO_BASE }}/content-service:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/dashboard:devel                         --amend ${{ env.IMAGE_REPO_BASE }}/dashboard:devel-arm64                      --amend ${{ env.IMAGE_REPO_BASE }}/dashboard:devel-amd64                            && docker manifest push ${{ env.IMAGE_REPO_BASE }}/dashboard:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/db-migrations:devel                     --amend ${{ env.IMAGE_REPO_BASE }}/db-migrations:devel-arm64                  --amend ${{ env.IMAGE_REPO_BASE }}/db-migrations:devel-amd64                        && docker manifest push ${{ env.IMAGE_REPO_BASE }}/db-migrations:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/docker-up:devel                         --amend ${{ env.IMAGE_REPO_BASE }}/docker-up:devel-arm64                      --amend ${{ env.IMAGE_REPO_BASE }}/docker-up:devel-amd64                            && docker manifest push ${{ env.IMAGE_REPO_BASE }}/docker-up:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ide-proxy:devel                         --amend ${{ env.IMAGE_REPO_BASE }}/ide-proxy:devel-arm64                      --amend ${{ env.IMAGE_REPO_BASE }}/ide-proxy:devel-amd64                            && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ide-proxy:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ide/code:devel                          --amend ${{ env.IMAGE_REPO_BASE }}/ide/code:devel-arm64                       --amend ${{ env.IMAGE_REPO_BASE }}/ide/code:devel-amd64                             && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ide/code:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ide/code-base:devel                     --amend ${{ env.IMAGE_REPO_BASE }}/ide/code-base:devel-arm64                  --amend ${{ env.IMAGE_REPO_BASE }}/ide/code-base:devel-amd64                        && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ide/code-base:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ide/goland:devel                        --amend ${{ env.IMAGE_REPO_BASE }}/ide/goland:devel-arm64                     --amend ${{ env.IMAGE_REPO_BASE }}/ide/goland:devel-amd64                           && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ide/goland:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ide/goland:devel                        --amend ${{ env.IMAGE_REPO_BASE }}/ide/goland:devel-arm64                     --amend ${{ env.IMAGE_REPO_BASE }}/ide/goland:devel-amd64                           && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ide/goland:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ide/intellij:devel                      --amend ${{ env.IMAGE_REPO_BASE }}/ide/intellij:devel-arm64                   --amend ${{ env.IMAGE_REPO_BASE }}/ide/intellij:devel-amd64                         && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ide/intellij:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ide/intellij:devel                      --amend ${{ env.IMAGE_REPO_BASE }}/ide/intellij:devel-arm64                   --amend ${{ env.IMAGE_REPO_BASE }}/ide/intellij:devel-amd64                         && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ide/intellij:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ide/phpstorm:devel                      --amend ${{ env.IMAGE_REPO_BASE }}/ide/phpstorm:devel-arm64                   --amend ${{ env.IMAGE_REPO_BASE }}/ide/phpstorm:devel-amd64                         && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ide/phpstorm:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ide/pycharm:devel                       --amend ${{ env.IMAGE_REPO_BASE }}/ide/pycharm:devel-arm64                    --amend ${{ env.IMAGE_REPO_BASE }}/ide/pycharm:devel-amd64                          && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ide/pycharm:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ide/pycharm:devel                       --amend ${{ env.IMAGE_REPO_BASE }}/ide/pycharm:devel-arm64                    --amend ${{ env.IMAGE_REPO_BASE }}/ide/pycharm:devel-amd64                          && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ide/pycharm:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/image-builder-mk3:devel                 --amend ${{ env.IMAGE_REPO_BASE }}/image-builder-mk3:devel-arm64              --amend ${{ env.IMAGE_REPO_BASE }}/image-builder-mk3:devel-amd64                    && docker manifest push ${{ env.IMAGE_REPO_BASE }}/image-builder-mk3:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/image-builder-mk3/bob:devel             --amend ${{ env.IMAGE_REPO_BASE }}/image-builder-mk3/bob:devel-arm64          --amend ${{ env.IMAGE_REPO_BASE }}/image-builder-mk3/bob:devel-amd64                && docker manifest push ${{ env.IMAGE_REPO_BASE }}/image-builder-mk3/bob:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/installation-telemetry:devel            --amend ${{ env.IMAGE_REPO_BASE }}/installation-telemetry:devel-arm64         --amend ${{ env.IMAGE_REPO_BASE }}/installation-telemetry:devel-amd64               && docker manifest push ${{ env.IMAGE_REPO_BASE }}/installation-telemetry:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/local-app:devel                         --amend ${{ env.IMAGE_REPO_BASE }}/local-app:devel-arm64                      --amend ${{ env.IMAGE_REPO_BASE }}/local-app:devel-amd64                            && docker manifest push ${{ env.IMAGE_REPO_BASE }}/local-app:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/local-app:devel                         --amend ${{ env.IMAGE_REPO_BASE }}/local-app:devel-arm64                      --amend ${{ env.IMAGE_REPO_BASE }}/local-app:devel-amd64                            && docker manifest push ${{ env.IMAGE_REPO_BASE }}/local-app:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/openvsx-proxy:devel                     --amend ${{ env.IMAGE_REPO_BASE }}/openvsx-proxy:devel-arm64                  --amend ${{ env.IMAGE_REPO_BASE }}/openvsx-proxy:devel-amd64                        && docker manifest push ${{ env.IMAGE_REPO_BASE }}/openvsx-proxy:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/payment-endpoint:devel                  --amend ${{ env.IMAGE_REPO_BASE }}/payment-endpoint:devel-arm64               --amend ${{ env.IMAGE_REPO_BASE }}/payment-endpoint:devel-amd64                     && docker manifest push ${{ env.IMAGE_REPO_BASE }}/payment-endpoint:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/proxy:devel                             --amend ${{ env.IMAGE_REPO_BASE }}/proxy:devel-arm64                          --amend ${{ env.IMAGE_REPO_BASE }}/proxy:devel-amd64                                && docker manifest push ${{ env.IMAGE_REPO_BASE }}/proxy:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/registry-facade:devel                   --amend ${{ env.IMAGE_REPO_BASE }}/registry-facade:devel-arm64                --amend ${{ env.IMAGE_REPO_BASE }}/registry-facade:devel-amd64                      && docker manifest push ${{ env.IMAGE_REPO_BASE }}/registry-facade:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/seccomp-profile-installer:devel         --amend ${{ env.IMAGE_REPO_BASE }}/seccomp-profile-installer:devel-arm64      --amend ${{ env.IMAGE_REPO_BASE }}/seccomp-profile-installer:devel-amd64            && docker manifest push ${{ env.IMAGE_REPO_BASE }}/seccomp-profile-installer:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/server:devel                            --amend ${{ env.IMAGE_REPO_BASE }}/server:devel-arm64                         --amend ${{ env.IMAGE_REPO_BASE }}/server:devel-amd64                               && docker manifest push ${{ env.IMAGE_REPO_BASE }}/server:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/service-waiter:devel                    --amend ${{ env.IMAGE_REPO_BASE }}/service-waiter:devel-arm64                 --amend ${{ env.IMAGE_REPO_BASE }}/service-waiter:devel-amd64                       && docker manifest push ${{ env.IMAGE_REPO_BASE }}/service-waiter:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/supervisor:devel                        --amend ${{ env.IMAGE_REPO_BASE }}/supervisor:devel-arm64                     --amend ${{ env.IMAGE_REPO_BASE }}/supervisor:devel-amd64                           && docker manifest push ${{ env.IMAGE_REPO_BASE }}/supervisor:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/workspacekit:devel                      --amend ${{ env.IMAGE_REPO_BASE }}/workspacekit:devel-arm64                   --amend ${{ env.IMAGE_REPO_BASE }}/workspacekit:devel-amd64                         && docker manifest push ${{ env.IMAGE_REPO_BASE }}/workspacekit:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ws-daemon:devel                         --amend ${{ env.IMAGE_REPO_BASE }}/ws-daemon:devel-arm64                      --amend ${{ env.IMAGE_REPO_BASE }}/ws-daemon:devel-amd64                            && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ws-daemon:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ws-manager:devel                        --amend ${{ env.IMAGE_REPO_BASE }}/ws-manager:devel-arm64                     --amend ${{ env.IMAGE_REPO_BASE }}/ws-manager:devel-amd64                           && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ws-manager:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ws-manager-bridge:devel                 --amend ${{ env.IMAGE_REPO_BASE }}/ws-manager-bridge:devel-arm64              --amend ${{ env.IMAGE_REPO_BASE }}/ws-manager-bridge:devel-amd64                    && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ws-manager-bridge:devel  
            docker manifest create ${{ env.IMAGE_REPO_BASE }}/ws-proxy:devel                          --amend ${{ env.IMAGE_REPO_BASE }}/ws-proxy:devel-arm64                       --amend ${{ env.IMAGE_REPO_BASE }}/ws-proxy:devel-amd64                             && docker manifest push ${{ env.IMAGE_REPO_BASE }}/ws-proxy:devel  
            "
