name: Build on Push
on: [push]

env:
  REGISTRY: ghcr.io
  DO_PUBLISH: "false"
  publishToNPM: "false"
  SEGMENT_IO_TOKEN: ""
  version: "devel"
  LEEWAY_YARN_MUTEX: "file"
  LEEWAY_WORKSPACE_ROOT: "/github/workspace"
  JAVA_HOME: "/home/gitpod/.sdkman/candidates/java/current"
  # components/dashboard:app need this
  CI: "false"
  BUILD_IMAGE: ghcr.io/zcube/workspace-images/gitpod-dev:arm64
  IMAGE_REPO_BASE: ghcr.io/zcube/gitpod

jobs:
  build-gitpod-amd64:
    runs-on: [self-hosted, linux, x64]
    env:
      GOARCH: amd64
      LEEWAY_REMOTE_CACHE_BUCKET: amd64
      LEEWAY_REMOTE_CACHE_STORAGE: MINIO
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.APP }}
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Filter test job 1
        shell: bash
        run: sed -i 's/[-] test[:]docker/#- test:docker/g' components/BUILD.yaml
      - name: Filter test job 2
        shell: bash
        run: find . | grep BUILD.yaml | xargs -n 1 sed -i 's/[-] [:]dbtest/#- :dbtest/g'
      - name: Change docker tag
        shell: bash
        run: find . | grep BUILD.yaml | xargs -n 1 sed -i 's/commit[-]/commit-${{ env.GOARCH }}-/g'
      - name: Prevent permission error
        shell: bash
        run: sudo chmod 777 /var/run/docker.sock
      - name: build
        uses: docker://ghcr.io/zcube/workspace-images/gitpod-dev:arm64
        with:
          args: |
            /bin/bash -c "sudo chown gitpod:gitpod -R /github/home/ &&
            yarn config set network-timeout 600000 -g &&
            mc config host add minio http://nas.zcube.kr:55090 ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }} &&
            docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} &&
            leeway -DSEGMENT_IO_TOKEN=${{ env.SEGMENT_IO_TOKEN }} -DpublishToNPM=${{ env.publishToNPM }} -DimageRepoBase=${{ env.IMAGE_REPO_BASE }} -Dversion=${{ env.version }}-${{ env.GOARCH }} build components:all-docker --dont-test --dont-retag -j 4"

  build-gitpod-arm64:
    runs-on: [self-hosted, linux, ARM64]
    env:
      GOARCH: arm64
      LEEWAY_REMOTE_CACHE_BUCKET: arm64
      LEEWAY_REMOTE_CACHE_STORAGE: MINIO
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.APP }}
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Filter test job 1
        shell: bash
        run: sed -i 's/[-] test[:]docker/#- test:docker/g' components/BUILD.yaml
      - name: Filter test job 2
        shell: bash
        run: find . | grep BUILD.yaml | xargs -n 1 sed -i 's/[-] [:]dbtest/#- :dbtest/g'
      - name: Change docker tag
        shell: bash
        run: find . | grep BUILD.yaml | xargs -n 1 sed -i 's/commit[-]/commit-${{ env.GOARCH }}-/g'
      - name: Prevent permission error
        shell: bash
        run: sudo chmod 777 /var/run/docker.sock
      - name: build
        uses: docker://ghcr.io/zcube/workspace-images/gitpod-dev:arm64
        with:
          args: |
            /bin/bash -c "sudo chown gitpod:gitpod -R /github/home/ &&
            yarn config set network-timeout 600000 -g &&
            mc config host add minio http://nas.zcube.kr:55090 ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }} &&
            docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} &&
            leeway -DSEGMENT_IO_TOKEN=${{ env.SEGMENT_IO_TOKEN }} -DpublishToNPM=${{ env.publishToNPM }} -DimageRepoBase=${{ env.IMAGE_REPO_BASE }} -Dversion=${{ env.version }}-${{ env.GOARCH }} build components:all-docker --dont-test --dont-retag -j 4"
